// Generated by scripts/update-app-store-rating.mjs.
// Sources: https://itunes.apple.com/lookup?id=6760192003&country=cn, https://itunes.apple.com/lookup?id=6760192003&country=jp
export const appStoreRatings = {
	"zh": {
		"appId": "6760192003",
		"country": "cn",
		"average": 4.59755,
		"averageDisplay": "4.6",
		"count": 82,
		"countDisplay": "82 个评分",
		"source": "https://itunes.apple.com/lookup?id=6760192003&country=cn",
		"updatedAt": "2026-06-04T02:19:45.535Z"
	},
	"ja": {
		"appId": "6760192003",
		"country": "jp",
		"average": 5,
		"averageDisplay": "5.0",
		"count": 1,
		"countDisplay": "1件の評価",
		"source": "https://itunes.apple.com/lookup?id=6760192003&country=jp",
		"updatedAt": "2026-06-04T02:19:45.692Z"
	}
} as const;
