// Generated by scripts/update-app-store-rating.mjs.
// Sources: https://itunes.apple.com/lookup?id=6760192003&country=cn, https://itunes.apple.com/lookup?id=6760192003&country=jp
export const appStoreRatings = {
	"zh": {
		"appId": "6760192003",
		"country": "cn",
		"average": 4.60606,
		"averageDisplay": "4.6",
		"count": 99,
		"countDisplay": "99 个评分",
		"source": "https://itunes.apple.com/lookup?id=6760192003&country=cn",
		"updatedAt": "2026-07-16T14:18:23.262Z"
	},
	"ja": {
		"appId": "6760192003",
		"country": "jp",
		"average": 3,
		"averageDisplay": "3.0",
		"count": 2,
		"countDisplay": "2件の評価",
		"source": "https://itunes.apple.com/lookup?id=6760192003&country=jp",
		"updatedAt": "2026-07-16T14:18:23.486Z"
	}
} as const;
