// Generated by scripts/update-app-store-rating.mjs.
// Source: https://itunes.apple.com/lookup?id=6760192003&country=cn
export const appStoreRatings = {
	"zh": {
		"appId": "6760192003",
		"country": "cn",
		"average": 4.58228,
		"averageDisplay": "4.6",
		"count": 79,
		"countDisplay": "79 个评分",
		"source": "https://itunes.apple.com/lookup?id=6760192003&country=cn",
		"updatedAt": "2026-05-27T11:10:10.392Z"
	}
} as const;
